### PR TITLE
fix: Change teams params to be comma-separated

### PR DESCRIPTION
**Pull request by mrfyda**

### CODE REVIEW

**Review by prcr — APPROVED** [review]
Uuh, good catch! :raised_hands:

**Review by prcr — COMMENTED** [review]
Won't it be confusing to users having to pass a comma-separated list for the teams, but a space-separated list for the commit identifiers? :thinking: 

https://github.com/codacy/pulse-user-docs/pull/73/files#diff-66278dc8e9255c21f197c5e1cdafcf2919af010a4480e4223d6b21b2539b36f7R188-L189

**Comment by mrfyda** [comment]
> Won't it be confusing to users having to pass a comma-separated list for the teams, but a space-separated list for the commit identifiers? 🤔
> 
> For example: https://github.com/codacy/pulse-user-docs/blame/master/docs/cli/cli.md#L188-L189

I'm not sure (cc @claudiacodacy)

@afsmeira was there a reason for the encodings to be different?

**Comment by claudiacodacy** [comment]
> > Won't it be confusing to users having to pass a comma-separated list for the teams, but a space-separated list for the commit identifiers? 🤔
> > For example: https://github.com/codacy/pulse-user-docs/blame/master/docs/cli/cli.md#L188-L189
> 
> I'm not sure (cc @claudiacodacy)

Not sure if this is relevant, but at least on the event log, Meira had displayed both separated by commas. Not sure if relevant since this is not the UI 💭 
https://github.com/codacy/pulse/pull/679

**Comment by prcr** [comment]
We should merge this fix in the meantime, and consider if we want to change the syntax at a later time. :+1:

**Pull request merged**
