### PR TITLE
feature: Link back to the Pulse app

### PR DESCRIPTION
**Pull request by mrfyda**
Screenshot 2021-03-05 at 10 45 21

### CODE REVIEW

**Review by rtfpessoa — APPROVED** [review]

**Comment by rtfpessoa** [comment]
@mrfyda can we add hotjar here so we can track users between the two pages?

**Comment by mrfyda** [comment]
we already do

**Review by pauloribeiro-codacy — CHANGES_REQUESTED** [review]
I like this idea, however, there's an easier way to achieve the same effect just by updating the `mkdocs.yml` file as you can also override the name of the "repo" and define a custom icon directly there (see [here](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/)):

```yml
repo_url: https://app.pulse.codacy.com/
repo_name: Back to the Pulse app

[...]

 theme:
  icon:
    repo: fontawesome/regular/arrow-alt-circle-right
```

This way, the whole link definition is centralized in a single place.

**Review by pauloribeiro-codacy — APPROVED** [review]
:shipit:

**Pull request merged**
